name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ssh_key_client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-musl
    - name: Build ssh_key_client
      run: cargo build --release --target=x86_64-unknown-linux-musl
      working-directory: ./ssh_key_client


  build_ssh_key_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-musl
    - name: Build ssh_key_server
      run: cargo build --release --target=x86_64-unknown-linux-musl
      working-directory: ./ssh_key_server

